accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        "signup/",
        views.CustomSignupView.as_view(),
        name="signup",
    ),
    path("email/change/", views.EmailChangeView.as_view(), name="account_email_change"),
    path(
        "email/change/done/",
        views.EmailChangeDoneView.as_view(),
        name="account_email_change_done",
    ),
    path(
        "password/change/",
        views.CustomPasswordChangeView.as_view(),
        name="change_password",
    ),
]

main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("home", views.HomeView.as_view(), name="home"),
    path("product_list/", views.ProductListView.as_view(), name="product_list"),
    path(
        "product_detail/<int:pk>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("like/<int:pk>/", views.product_like, name="like"),
    path("unlike/<int:pk>/", views.product_unlike, name="unlike"),
    path("product_sell/", views.product_sell, name="product_sell"),
    path(
        "purchase_confirmation/<int:pk>/",
        views.PurchaseConfirmationView.as_view(),
        name="purchase_confirmation",
    ),
    path(
        "purchase_procedure/address/", views.InputAddressView.as_view(), name="address"
    ),
    path(
        "purchase_procedure/payment/", views.InputPaymentView.as_view(), name="payment"
    ),
    path(
        "purchase_procedure/final_confirmation/",
        views.CreateCheckoutView.as_view(),
        name="final_confirmation",
    ),
    path(
        "change_delivery_status/<int:pk>/",
        views.change_delivery_status,
        name="change_delivery_status",
    ),
    path("delete_product/<int:pk>/", views.delete_product, name="delete_product"),
    path(
    "account/",
    views.AccountView.as_view(),
    name="account",
    ),
    path(
        "terms/",
        views.TermsView.as_view(),
        name="terms",
    ),
    path(
        "privacy_policy/",
        views.PrivacyPolicyView.as_view(),
        name="privacy_policy",
    ),
    path(
        "account_delete/",
        views.AccountDeleteView.as_view(),
        name="account_delete",
    ),
    path(
        "account_delete_done/",
        views.AccountDeleteDoneView.as_view(),
        name="account_delete_done",
    ),
    path(
    "account_detail/<int:pk>",
    views.AccountDetailView.as_view(),
    name="account_detail",
    ),
    path("liked_list/", views.ProductLikedListView.as_view(), name="liked_list"),
    path(
        "exhibited_list/", views.ProductExibitListView.as_view(), name="exhibited_list"
    ),
    path(
    "purchased_list",
    views.ProductPurchasedListView.as_view(),
    name="purchased_list",
    ),
    path(
    "account_update",
    views.AccountUpdateView.as_view(),
    name="account_update",
    ),
    path("notification/", views.NotificationView.as_view(), name="notification"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.templatetags.static import static


class User(AbstractUser):
    icon = models.ImageField(
        upload_to="user_icon/",
        blank=True,
    )
    point = models.IntegerField(default=0)
    profile = models.TextField(max_length=500, blank=True)

    def icon_url(self):
        if self.icon:
            return self.icon.url
        return static("main/img/default-user_icon.png")

main/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

User = get_user_model()

class Genre(models.Model):
    name = models.CharField(max_length=20)
    image = models.ImageField(
        upload_to="genre_image/",
        blank=True,
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    SALES_STATUS_CHOICES = [
        ("on_display", "出品中"),
        ("sold", "売却済"),
    ]
    PRODUCT_STATUS_CHOICES = [
        ("new", "新品、未使用"),
        ("almost_new", "未使用に近い"),
        ("little_blemish", "目立った傷や汚れなし"),
        ("a_little_blemish", "やや傷や汚れあり"),
        ("some_blemish", "傷や汚れあり"),
        ("bad", "全体的に状態が悪い"),
    ]
    exhibitor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="products_exhibited"
    )
    name = models.CharField(max_length=30)
    explanation = models.TextField(max_length=500)
    genre = models.ForeignKey(
        Genre, on_delete=models.SET_NULL, null=True, related_name="products"
    )
    product_status = models.CharField(max_length=20, choices=PRODUCT_STATUS_CHOICES)
    sales_status = models.CharField(max_length=20, choices=SALES_STATUS_CHOICES)
    value = models.IntegerField(validators=[MinValueValidator(300), MaxValueValidator(999999)])
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"商品名:{self.name},出品者:{self.exhibitor}"


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_images"
    )
    image = models.ImageField(
        upload_to="product_image/",
        blank=True,
    )

    def __str__(self):
        return f"{self.image}"


class Address(models.Model):
    PREFECTURES = (
        ("北海道", "北海道"),
        ("青森県", "青森県"),
        ("岩手県", "岩手県"),
        ("宮城県", "宮城県"),
        ("秋田県", "秋田県"),
        ("山形県", "山形県"),
        ("福島県", "福島県"),
        ("茨城県", "茨城県"),
        ("栃木県", "栃木県"),
        ("群馬県", "群馬県"),
        ("埼玉県", "埼玉県"),
        ("千葉県", "千葉県"),
        ("東京都", "東京都"),
        ("神奈川県", "神奈川県"),
        ("新潟県", "新潟県"),
        ("富山県", "富山県"),
        ("石川県", "石川県"),
        ("福井県", "福井県"),
        ("山梨県", "山梨県"),
        ("長野県", "長野県"),
        ("岐阜県", "岐阜県"),
        ("静岡県", "静岡県"),
        ("愛知県", "愛知県"),
        ("三重県", "三重県"),
        ("滋賀県", "滋賀県"),
        ("京都府", "京都府"),
        ("大阪府", "大阪府"),
        ("兵庫県", "兵庫県"),
        ("奈良県", "奈良県"),
        ("和歌山県", "和歌山県"),
        ("鳥取県", "鳥取県"),
        ("島根県", "島根県"),
        ("岡山県", "岡山県"),
        ("広島県", "広島県"),
        ("山口県", "山口県"),
        ("徳島県", "徳島県"),
        ("香川県", "香川県"),
        ("愛媛県", "愛媛県"),
        ("高知県", "高知県"),
        ("福岡県", "福岡県"),
        ("佐賀県", "佐賀県"),
        ("長崎県", "長崎県"),
        ("熊本県", "熊本県"),
        ("大分県", "大分県"),
        ("宮崎県", "宮崎県"),
        ("鹿児島県", "鹿児島県"),
        ("沖縄県", "沖縄県"),
    )
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    first_name_kana = models.CharField(max_length=20)
    last_name_kana = models.CharField(max_length=20)
    postal_code = models.CharField(max_length=7)
    prefecture = models.CharField(max_length=4, choices=PREFECTURES)
    address = models.CharField(max_length=255)
    tel = models.CharField(max_length=11)


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="payments")
    stripe_charge_id = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.stripe_charge_id}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes_given")
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="likes_received"
    )

    def __str__(self):
        return f"いいねしたユーザー:{self.user},いいねの対象:{self.product.name}"


class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ("before_shipping", "発送待ち"),
        ("shipped", "発送済み"),
        ("delivered", "配達済"),
    ]
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name="orders_received"
    )
    price = models.IntegerField()
    purchaser = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="orders_given"
    )
    order_time = models.DateTimeField(auto_now_add=True)
    delivery_status = models.CharField(choices=ORDER_STATUS_CHOICES, max_length=20)
    address = models.OneToOneField(
        Address, on_delete=models.CASCADE, related_name="orders_delivered_to"
    )
    payment = models.OneToOneField(
        Payment, on_delete=models.CASCADE, related_name="orders_paid_with"
    )

    def __str__(self):
        return f"購入者:{self.product.name},配達状況{self.delivery_status}"


class Notification(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notifications_received"
    )
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="notifications_given"
    )
    is_action = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}への{'アクション' if self.is_action == True else 'お知らせ'}"

accounts/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from .models import User


class CustomSignupForm(SignupForm):
    """会員登録用フォーム"""
    checkbox = forms.BooleanField(
        label="利用規約に同意する",
        error_messages={"required": "利用規約に同意する必要があります"},
        required=True,
    )

    fields = ["username", "email", "password1", "password2", "checkbox"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["class"] = "form"
        self.fields["email"].widget.attrs["class"] = "form"
        self.fields["password1"].widget.attrs["class"] = "form"
        self.fields["password2"].widget.attrs["class"] = "form"

    def clean_checkbox(self):
        checkbox = self.cleaned_data.get("checkbox")
        if not checkbox:
            raise forms.ValidationError(
                self.fields["checkbox"].error_messages["required"]
            )
        return checkbox
    
class EmailChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email",)
        widgets = {
            "email": forms.TextInput(
                attrs={
                    "placeholder": "新しいメールアドレス",
                }
            )
        }

    def clean_email(self):
        new_email = self.cleaned_data["email"]
        user = User.objects.filter(email__iexact=new_email)
        if user.exists():
            raise ValidationError("このメールアドレスは既に使われています。")
        return new_email

main/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from .models import Product, ProductImage, Address
import re

User = get_user_model()


class ProductSearchForm(forms.Form):
    keyword = forms.CharField(
        label="検索",
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "商品を検索"}),
    )

class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ("image",)
        labels = {"image": ""}


ProductImageFormSet = forms.modelformset_factory(
    ProductImage,
    form=ProductImageForm,
    extra=5,
)


class ProductSellForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            "genre",
            "product_status",
            "name",
            "explanation",
            "value",
        )
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "placeholder": "商品名",
                    "onkeyup": "showNameLength(value);",
                }
            ),
            "explanation": forms.Textarea(
                attrs={
                    "placeholder": "商品の説明",
                    "onkeyup": "showExplanationLength(value);",
                }
            ),
            "value": forms.NumberInput(
                attrs={"placeholder": "販売価格（¥）"}
            ),
        }

class CustomProductImageFormSet(ProductImageFormSet):
    def clean(self):
        super().clean()
        has_image = False
        for form in self.forms:
            if form.cleaned_data.get("image"):
                has_image = True
                break
        if not has_image:
            raise ValidationError("1枚以上の画像を選択してください。")
        
class PaymentForm(forms.Form):
    def __init__(self, price=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.price = price
        self.fields["total_amount"].initial = self.price

    point = forms.IntegerField(widget=forms.HiddenInput(attrs={"value": "0"}))
    total_amount = forms.IntegerField(widget=forms.HiddenInput())

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = (
            "last_name",
            "first_name",
            "last_name_kana",
            "first_name_kana",
            "postal_code",
            "prefecture",
            "address",
            "tel",
        )
        widgets = {
            "last_name": forms.TextInput(attrs={"placeholder": "姓"}),
            "first_name": forms.TextInput(attrs={"placeholder": "名"}),
            "last_name_kana": forms.TextInput(attrs={"placeholder": "姓カナ"}),
            "first_name_kana": forms.TextInput(attrs={"placeholder": "名カナ"}),
            "postal_code": forms.TextInput(attrs={"placeholder": "郵便番号（数字）"}),
            "prefecture": forms.Select(attrs={"placeholder": "都道府県"}),
            "address": forms.TextInput(attrs={"placeholder": "住所"}),
            "tel": forms.TextInput(attrs={"placeholder": "電話番号"}),
        }

    def clean_first_name_kana(self):
        first_name_kana = self.cleaned_data["first_name_kana"]
        if not re.match(r"^[ァ-ヴー]*$", first_name_kana):
            raise ValidationError("カタカナのみ入力してください。")
        return first_name_kana

    def clean_last_name_kana(self):
        last_name_kana = self.cleaned_data["last_name_kana"]
        if not re.match(r"^[ァ-ヴー]*$", last_name_kana):
            raise ValidationError("カタカナのみ入力してください。")
        return last_name_kana

    def clean_postal_code(self):
        postal_code = self.cleaned_data["postal_code"]
        if len(postal_code) != 7 or not postal_code.isdigit():
            raise ValidationError("郵便番号には7桁の数字を入力してください。")
        return postal_code

    def clean_tel(self):
        tel = self.cleaned_data["tel"]
        if not (10 <= len(tel) <= 11) or not tel.isdigit():
            raise ValidationError("電話番号には10桁または11桁の数字を入力してください。")
        return tel

class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("icon", "username", "profile")
        labels = {
            "username": "ユーザー名",
            "profile": "紹介文",
        }
        widgets = {
            "icon": forms.FileInput(attrs={"onchange": "previewImage(this);"}),
            "username": forms.TextInput(attrs={"onkeyup": "showUsernameLength(value);"}),
            "profile": forms.Textarea(attrs={"onkeyup": "showProfileLength(value);"}),
        }

accounts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import DeleteView, FormView, TemplateView
from allauth.account.views import PasswordChangeView, SignupView
from .forms import CustomSignupForm, EmailChangeForm
from django.urls import reverse_lazy

class CustomSignupView(SignupView):
    templates_name = "account/signup.html"
    form_class = CustomSignupForm

class EmailChangeView(FormView):
    form_class = EmailChangeForm
    success_url = reverse_lazy("account_email_change_done")
    template_name = "account/email_change.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_email"] = self.request.user.email
        return context

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data["email"]
        user.email = new_email
        user.save()
        return super().form_valid(form)

class EmailChangeDoneView(TemplateView):
    template_name = "account/email_change_done.html"

class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy("main:account")

main/templates/main/account.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'main/css/account.css' %}">
{% endblock %}

{% block content %}
<div class="account">
    <a href="{% url 'main:account_detail' request.user.id %}" class="account-container">
        <div class="account-icon">
            <img src="{{ user.icon_url }}">
        </div>
        <div class="account-detail-wrapper">
            <div class="account-detail-items">
                <div class="account-username">
                    {{ user.username }}
                </div>
                <div class="account-point">
                    {{ user.point }} pt保有
                </div>
            </div>
            <i class="fa-solid fa-chevron-right"></i>
        </div>
    </a>
    <div class="products-control-container">
        <p class="products-control-title">商品管理</p>
        <a href="{% url 'main:liked_list' %}" class="products-control-item">
            <i class="fa-regular fa-heart fa-fw"></i>
            <p class="products-control-text">いいねした商品</p>
        </a>
        <a href="{% url 'main:exhibited_list' %}" class="products-control-item">
            <i class="fa-solid fa-store fa-fw"></i>
            <p class="products-control-text">出品した商品</p>
        </a>
        <a href="{% url 'main:purchased_list' %}" class="products-control-item">
            <i class="fa-solid fa-bag-shopping fa-fw"></i>
            <p class="products-control-text">購入した商品</p>
        </a>
    </div>
    <div class="account-settings-container">
        <p class="account-settings-title">アカウントの設定</p>
        <a href="{% url 'account_email_change' %}" class="account-settings-item">
            <i class="fa-regular fa-envelope fa-fw"></i>
            <p class="account-settings-text">メールアドレスの変更</p>
        </a>
        <a href="{% url 'change_password' %}" class="account-settings-item">
            <i class="fa-solid fa-asterisk fa-fw"></i>
            <p class="account-settings-text">パスワードの変更</p>
        </a>
    </div>
    <div class="others-container">
        <div class="others-item rule">
            <a href="{% url 'main:terms' %}" class="terms">利用規約</a>
            <p>・</p>
            <a href="{% url 'main:privacy_policy' %}" class="policy">プライバシーポリシー</a>
        </div>
        <div class="others-item">
            <form action="{% url 'account_logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="logout-link">ログアウト</button>
            </form>
        </div>
        <div class="others-item">
            <p class="account-delete-text">アカウントの削除は</p>
            <a href="{% url 'main:account_delete' %}" class="account-delete-link">こちら</a>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>フリマアプリ</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    {% block extra_style %}{% endblock %}
</head>

<body>
    {% block header %}
    {% if request.user.is_authenticated %}
    <header class="header">
        <div class="header__item">
            <div class="header__title">
                {% block header_title %}<a href="{% url 'main:home' %}">FreeMa</a>{% endblock %}
            </div>
            <div class="header__form">
                <form action="{% url 'main:product_list' %}" method="GET">
                    {{ search_form.keyword }}
                </form>
            </div>
        </div>
    </header>
    {% endif %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% if request.user.is_authenticated %}
    <footer class="footer">
        <div class="footer__item">
            <a href="{% url 'main:home' %}" class="footer__link">
                <div class="footer__icon"><i class="fas fa-home"></i></div>
                <div class="footer__label">ホーム</div>
            </a>
        </div>
        <div class="footer__item">
            <a href="{% url 'main:product_sell' %}" class="footer__link">
                <div class="footer__icon"><i class="far fa-times-circle upload-icon"></i></div>
                <div class="footer__label">出品</div>
            </a>
        </div>
        <div class="footer__item">
            <a href="{% url 'main:notification' %}" class="footer__link">
                <div class="footer__icon"><i class="fa-regular fa-bell"></i></div>
                <div class="footer__label">通知</div>
            </a>
        </div>
        <div class="footer__item">
            <a href="{% url 'main:account' %}" class="footer__link">
                <div class="footer__icon"><i class="fas fa-user"></i></div>
                <div class="footer__label">アカウント</div>
            </a>
        </div>
    </footer>
    {% else %}
    <div class="others">
        <div class="rules">
            <a href="" class="terms">利用規約</a>・
            <a href="" class="policy">プライバシーポリシー</a>
        </div>
    </div>
    {% endif %}
    {% endblock %}
    {% block extra_js %}{% endblock %}
</body>

</html>

main/templates/main/notification.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'main/css/notification.css' %}">
{% endblock %}

{% block content %}
<div class="notification-list-container">
    <div class="tab-container">
        <div class="tab active" data-is-action="true">アクション</div>
        <div class="tab" data-is-action="false">お知らせ</div>
        <div class="underline"></div>
    </div>
    <ul class="notification-list">
        {% for notification in notifications %}
        <li class="notification-item">
            <a href="{% url 'main:product_detail' notification.order.product.pk %}">
                <div class="notification-wrapper">
                    <img src="{{ notification.order.product.product_images.all.0.image.url }}" alt="" class="product-img">
                    <div class="notification-message-wrapper">
                        {% if notification.is_action %}
                        <p class="notification-message">商品を発送して、発送を完了させましょう。</p>
                        {% else %}
                        <p class="notification-message">{{ notification.order.product.name }}が発送されました。</p>
                        {% endif %}
                        <p class="notification-time">{{ notification.created_at }}</p>
                    </div>
                </div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'main/js/notification.js' %}"></script>
{% endblock %}

main/templates/main/product_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css">
<link rel="stylesheet" href="{% static 'main/css/product_detail.css' %}">
{% endblock %}

{% block content %}
<div class="product-overview-container">
    {# 購入者に対するメッセージ #}
    {% if item.orders_received.purchaser == request.user %}
        {% if item.orders_received.delivery_status == "before_shipping" %}
        <div class="order-information">
            <p class="message-title">ただいま発送待ち</p>
            <p class="message-detail">出品者が発送して届くまでしばらくお待ちください。</p>
        </div>
        {% elif item.orders_received.delivery_status == "shipped" %}
        <div class="order-information">
            <p class="message-title">発送済み</p>
            <p class="message-detail">出品者は商品を発送しました。商品が届いたら受け取り報告を行ってください。</p>
        </div>
        {% elif item.orders_received.delivery_status == "delivered" %}
        <div class="order-information">
            <p class="message-title">取引が完了しました</p>
            <p class="message-detail">ご利用ありがとうございました。</p>
        </div>
        {% endif %}
    {# 出品者に対するメッセージ #}
    {% elif item.exhibitor == request.user %}
        {% if item.orders_received.delivery_status == "before_shipping" %}
        <div class="order-information">
            <p class="message-title">ただいま発送待ち</p>
            <p class="message-detail">発送して完了報告を行ってください。</p>
        </div>
        {% elif item.orders_received.delivery_status == "shipped" %}
        <div class="order-information">
            <p class="message-title">発送済み</p>
            <p class="message-detail">購入者が完了報告を行うまでしばらくお待ちください。</p>
        </div>
        {% elif item.orders_received.delivery_status == "delivered" %}
        <div class="order-information">
            <p class="message-title">取引が完了しました</p>
            <p class="message-detail">取引お疲れ様でした。</p>
        </div>
        {% endif %}
    {% endif %}
    <div class="swiper">
        <div class="swiper-wrapper">
            {% for product_image in item.product_images.all %}
            <div class="swiper-slide">
                <img src="{{ product_image.image.url }}">
                {% if item.sales_status != "on_display" %}
                <div class="bg-green">
                    <p class="sold">SOLD</p>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
    </div>
    <div class="product-detail-container">
        <div>
            <p class="product-name">{{ item.name }}</p>
            <div class="product-detail-wrapper">
                <p class="product-price">{{ item.value }}円</p>
            </div>
        </div>
        <div class="product-like-button">
            {% if item.is_liked %}
            <form method="POST" action="{% url 'main:unlike' item.pk %}">
                {% csrf_token %}
                <div class="like-container">
                    <button type="submit" class="product-unlike-btn"><i class="fa-solid fa-heart" style="color: #2B8F38;"></i></button>
                    <p class="like-count-liked">{{ item.likes_count }}</p>
                </div>
            </form>
            {% else %}
            <form method="POST" action="{% url 'main:like' item.pk %}">
                {% csrf_token %}
                <div class="like-container">
                    <button type="submit" class="product-like-btn"><i class="fa-regular fa-heart"></i></button>
                    <p class="like-count">{{ item.likes_count }}</p>
                </div>
            </form>
            {% endif %}
        </div>
    </div>
</div>
<hr>
<div class="product-description-container">
    <p class="section-title">商品の説明</p>
    <p class="product-description">{{ item.explanation }}</p>
    <p class="product-upload-time">{{ item.uploaded_at|date:"Y/m/j" }}</p>
</div>
<hr>
<div class="product-information-container">
    <p class="section-title">商品の情報</p>
    <div class="category-wrapper">
        <p class="category-section-title">カテゴリー</p>
        <p class="product-category">{{ item.genre.name }}</p>
    </div>
    <div class="status-wrapper">
        <p class="stauts-section-title">商品の状態</p>
        <p class="product-status">{{ item.get_product_status_display }}</p>
    </div>
</div>
<hr>
<div class="product-seller-container">
    <p class="section-title">出品者</p>
    <div class="seller-wrapper">
        <a href="">
            <img class="seller-img" src="{{ item.exhibitor.icon_url }}">
        </a>
        <p class="seller-name">{{ item.exhibitor.username }}</p>
    </div>
</div>
{% if item.sales_status == "on_display" and item.exhibitor != request.user %}
<a href="{% url 'main:purchase_confirmation' item.pk %}" class="product-buy-btn">購入手続きへ</a>
{% endif %}

{% if item.sales_status == "on_display" and item.exhibitor == request.user %}
<form action="{% url 'main:delete_product' item.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="delete-product-btn">出品を取り下げる</button>
</form>
{% endif %}

{% if item.exhibitor == request.user and item.orders_received.delivery_status == "before_shipping" %}
<form action="{% url 'main:change_delivery_status' item.orders_received.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="change-status-btn">発送完了を報告する</button>
</form>
{% endif %}
{% if item.orders_received.purchaser == request.user and item.orders_received.delivery_status == "shipped" %}
<form action="{% url 'main:change_delivery_status' item.orders_received.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="change-status-btn">受取完了を報告する</button>
</form>
{% endif %}
{% endblock %}

{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
<script src="{% static 'main/js/swiper.js' %}"></script>
{% endblock %}